// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"
	http "net/http"

	mock "github.com/stretchr/testify/mock"
	provider "github.com/tggo/cerber/internal/provider"
)

// Chatter is an autogenerated mock type for the Chatter type
type Chatter struct {
	mock.Mock
}

type Chatter_Expecter struct {
	mock *mock.Mock
}

func (_m *Chatter) EXPECT() *Chatter_Expecter {
	return &Chatter_Expecter{mock: &_m.Mock}
}

// Chat provides a mock function with given fields: ctx, openaiBody, stream, clientHeader
func (_m *Chatter) Chat(ctx context.Context, openaiBody []byte, stream bool, clientHeader http.Header) (*provider.Response, error) {
	ret := _m.Called(ctx, openaiBody, stream, clientHeader)

	if len(ret) == 0 {
		panic("no return value specified for Chat")
	}

	var r0 *provider.Response
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, []byte, bool, http.Header) (*provider.Response, error)); ok {
		return rf(ctx, openaiBody, stream, clientHeader)
	}
	if rf, ok := ret.Get(0).(func(context.Context, []byte, bool, http.Header) *provider.Response); ok {
		r0 = rf(ctx, openaiBody, stream, clientHeader)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*provider.Response)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, []byte, bool, http.Header) error); ok {
		r1 = rf(ctx, openaiBody, stream, clientHeader)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Chatter_Chat_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Chat'
type Chatter_Chat_Call struct {
	*mock.Call
}

// Chat is a helper method to define mock.On call
//   - ctx context.Context
//   - openaiBody []byte
//   - stream bool
//   - clientHeader http.Header
func (_e *Chatter_Expecter) Chat(ctx interface{}, openaiBody interface{}, stream interface{}, clientHeader interface{}) *Chatter_Chat_Call {
	return &Chatter_Chat_Call{Call: _e.mock.On("Chat", ctx, openaiBody, stream, clientHeader)}
}

func (_c *Chatter_Chat_Call) Run(run func(ctx context.Context, openaiBody []byte, stream bool, clientHeader http.Header)) *Chatter_Chat_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].([]byte), args[2].(bool), args[3].(http.Header))
	})
	return _c
}

func (_c *Chatter_Chat_Call) Return(_a0 *provider.Response, _a1 error) *Chatter_Chat_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Chatter_Chat_Call) RunAndReturn(run func(context.Context, []byte, bool, http.Header) (*provider.Response, error)) *Chatter_Chat_Call {
	_c.Call.Return(run)
	return _c
}

// Name provides a mock function with no fields
func (_m *Chatter) Name() string {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Name")
	}

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// Chatter_Name_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Name'
type Chatter_Name_Call struct {
	*mock.Call
}

// Name is a helper method to define mock.On call
func (_e *Chatter_Expecter) Name() *Chatter_Name_Call {
	return &Chatter_Name_Call{Call: _e.mock.On("Name")}
}

func (_c *Chatter_Name_Call) Run(run func()) *Chatter_Name_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *Chatter_Name_Call) Return(_a0 string) *Chatter_Name_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Chatter_Name_Call) RunAndReturn(run func() string) *Chatter_Name_Call {
	_c.Call.Return(run)
	return _c
}

// NewChatter creates a new instance of Chatter. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewChatter(t interface {
	mock.TestingT
	Cleanup(func())
}) *Chatter {
	mock := &Chatter{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
