// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
	credential "github.com/tggo/cerber/internal/credential"
)

// Refresher is an autogenerated mock type for the Refresher type
type Refresher struct {
	mock.Mock
}

type Refresher_Expecter struct {
	mock *mock.Mock
}

func (_m *Refresher) EXPECT() *Refresher_Expecter {
	return &Refresher_Expecter{mock: &_m.Mock}
}

// Refresh provides a mock function with given fields: ctx, refreshToken
func (_m *Refresher) Refresh(ctx context.Context, refreshToken string) (credential.OAuthTokens, error) {
	ret := _m.Called(ctx, refreshToken)

	if len(ret) == 0 {
		panic("no return value specified for Refresh")
	}

	var r0 credential.OAuthTokens
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (credential.OAuthTokens, error)); ok {
		return rf(ctx, refreshToken)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) credential.OAuthTokens); ok {
		r0 = rf(ctx, refreshToken)
	} else {
		r0 = ret.Get(0).(credential.OAuthTokens)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, refreshToken)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Refresher_Refresh_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Refresh'
type Refresher_Refresh_Call struct {
	*mock.Call
}

// Refresh is a helper method to define mock.On call
//   - ctx context.Context
//   - refreshToken string
func (_e *Refresher_Expecter) Refresh(ctx interface{}, refreshToken interface{}) *Refresher_Refresh_Call {
	return &Refresher_Refresh_Call{Call: _e.mock.On("Refresh", ctx, refreshToken)}
}

func (_c *Refresher_Refresh_Call) Run(run func(ctx context.Context, refreshToken string)) *Refresher_Refresh_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *Refresher_Refresh_Call) Return(_a0 credential.OAuthTokens, _a1 error) *Refresher_Refresh_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Refresher_Refresh_Call) RunAndReturn(run func(context.Context, string) (credential.OAuthTokens, error)) *Refresher_Refresh_Call {
	_c.Call.Return(run)
	return _c
}

// NewRefresher creates a new instance of Refresher. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewRefresher(t interface {
	mock.TestingT
	Cleanup(func())
}) *Refresher {
	mock := &Refresher{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
