// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"
	http "net/http"

	mock "github.com/stretchr/testify/mock"
	credential "github.com/tggo/cerber/internal/credential"
)

// Upstream is an autogenerated mock type for the Upstream type
type Upstream struct {
	mock.Mock
}

type Upstream_Expecter struct {
	mock *mock.Mock
}

func (_m *Upstream) EXPECT() *Upstream_Expecter {
	return &Upstream_Expecter{mock: &_m.Mock}
}

// CountTokens provides a mock function with given fields: ctx, body, cred, clientHeader
func (_m *Upstream) CountTokens(ctx context.Context, body []byte, cred *credential.Credential, clientHeader http.Header) (*http.Response, error) {
	ret := _m.Called(ctx, body, cred, clientHeader)

	if len(ret) == 0 {
		panic("no return value specified for CountTokens")
	}

	var r0 *http.Response
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, []byte, *credential.Credential, http.Header) (*http.Response, error)); ok {
		return rf(ctx, body, cred, clientHeader)
	}
	if rf, ok := ret.Get(0).(func(context.Context, []byte, *credential.Credential, http.Header) *http.Response); ok {
		r0 = rf(ctx, body, cred, clientHeader)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*http.Response)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, []byte, *credential.Credential, http.Header) error); ok {
		r1 = rf(ctx, body, cred, clientHeader)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Upstream_CountTokens_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CountTokens'
type Upstream_CountTokens_Call struct {
	*mock.Call
}

// CountTokens is a helper method to define mock.On call
//   - ctx context.Context
//   - body []byte
//   - cred *credential.Credential
//   - clientHeader http.Header
func (_e *Upstream_Expecter) CountTokens(ctx interface{}, body interface{}, cred interface{}, clientHeader interface{}) *Upstream_CountTokens_Call {
	return &Upstream_CountTokens_Call{Call: _e.mock.On("CountTokens", ctx, body, cred, clientHeader)}
}

func (_c *Upstream_CountTokens_Call) Run(run func(ctx context.Context, body []byte, cred *credential.Credential, clientHeader http.Header)) *Upstream_CountTokens_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].([]byte), args[2].(*credential.Credential), args[3].(http.Header))
	})
	return _c
}

func (_c *Upstream_CountTokens_Call) Return(_a0 *http.Response, _a1 error) *Upstream_CountTokens_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Upstream_CountTokens_Call) RunAndReturn(run func(context.Context, []byte, *credential.Credential, http.Header) (*http.Response, error)) *Upstream_CountTokens_Call {
	_c.Call.Return(run)
	return _c
}

// Send provides a mock function with given fields: ctx, body, stream, cred, clientHeader
func (_m *Upstream) Send(ctx context.Context, body []byte, stream bool, cred *credential.Credential, clientHeader http.Header) (*http.Response, error) {
	ret := _m.Called(ctx, body, stream, cred, clientHeader)

	if len(ret) == 0 {
		panic("no return value specified for Send")
	}

	var r0 *http.Response
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, []byte, bool, *credential.Credential, http.Header) (*http.Response, error)); ok {
		return rf(ctx, body, stream, cred, clientHeader)
	}
	if rf, ok := ret.Get(0).(func(context.Context, []byte, bool, *credential.Credential, http.Header) *http.Response); ok {
		r0 = rf(ctx, body, stream, cred, clientHeader)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*http.Response)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, []byte, bool, *credential.Credential, http.Header) error); ok {
		r1 = rf(ctx, body, stream, cred, clientHeader)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Upstream_Send_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Send'
type Upstream_Send_Call struct {
	*mock.Call
}

// Send is a helper method to define mock.On call
//   - ctx context.Context
//   - body []byte
//   - stream bool
//   - cred *credential.Credential
//   - clientHeader http.Header
func (_e *Upstream_Expecter) Send(ctx interface{}, body interface{}, stream interface{}, cred interface{}, clientHeader interface{}) *Upstream_Send_Call {
	return &Upstream_Send_Call{Call: _e.mock.On("Send", ctx, body, stream, cred, clientHeader)}
}

func (_c *Upstream_Send_Call) Run(run func(ctx context.Context, body []byte, stream bool, cred *credential.Credential, clientHeader http.Header)) *Upstream_Send_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].([]byte), args[2].(bool), args[3].(*credential.Credential), args[4].(http.Header))
	})
	return _c
}

func (_c *Upstream_Send_Call) Return(_a0 *http.Response, _a1 error) *Upstream_Send_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Upstream_Send_Call) RunAndReturn(run func(context.Context, []byte, bool, *credential.Credential, http.Header) (*http.Response, error)) *Upstream_Send_Call {
	_c.Call.Return(run)
	return _c
}

// NewUpstream creates a new instance of Upstream. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewUpstream(t interface {
	mock.TestingT
	Cleanup(func())
}) *Upstream {
	mock := &Upstream{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
